# Generated by Django 4.2.14 on 2024-07-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_plants_plant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='PlantsProducts',
        ),
    ]
